// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Entities;

namespace Model.Migrations
{
    [DbContext(typeof(EFBankContext))]
    [Migration("20220310135517_managerpersoneel_v2")]
    partial class managerpersoneel_v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Entities.Klant", b =>
                {
                    b.Property<int>("KlantNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Klantnummer")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("KlantNr");

                    b.ToTable("Klanten");

                    b.HasData(
                        new
                        {
                            KlantNr = 1,
                            Voornaam = "Marge"
                        },
                        new
                        {
                            KlantNr = 2,
                            Voornaam = "Homer"
                        },
                        new
                        {
                            KlantNr = 3,
                            Voornaam = "Lisa"
                        },
                        new
                        {
                            KlantNr = 4,
                            Voornaam = "Maggie"
                        },
                        new
                        {
                            KlantNr = 5,
                            Voornaam = "Bart"
                        });
                });

            modelBuilder.Entity("Model.Entities.Personeelslid", b =>
                {
                    b.Property<int>("PersoneelsNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ManagerNr")
                        .HasColumnType("int");

                    b.Property<string>("Voornaam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersoneelsNr");

                    b.HasIndex("ManagerNr");

                    b.ToTable("Personeelsleden");

                    b.HasData(
                        new
                        {
                            PersoneelsNr = 1,
                            Voornaam = "Diane"
                        },
                        new
                        {
                            PersoneelsNr = 2,
                            ManagerNr = 1,
                            Voornaam = "Mary"
                        },
                        new
                        {
                            PersoneelsNr = 3,
                            ManagerNr = 1,
                            Voornaam = "Jeff"
                        },
                        new
                        {
                            PersoneelsNr = 4,
                            ManagerNr = 2,
                            Voornaam = "William"
                        },
                        new
                        {
                            PersoneelsNr = 5,
                            ManagerNr = 2,
                            Voornaam = "Gerard"
                        },
                        new
                        {
                            PersoneelsNr = 6,
                            ManagerNr = 2,
                            Voornaam = "Anthony"
                        },
                        new
                        {
                            PersoneelsNr = 7,
                            ManagerNr = 6,
                            Voornaam = "Leslie"
                        },
                        new
                        {
                            PersoneelsNr = 8,
                            ManagerNr = 6,
                            Voornaam = "July"
                        },
                        new
                        {
                            PersoneelsNr = 9,
                            ManagerNr = 6,
                            Voornaam = "Steve"
                        },
                        new
                        {
                            PersoneelsNr = 10,
                            ManagerNr = 6,
                            Voornaam = "Foon Yue"
                        },
                        new
                        {
                            PersoneelsNr = 11,
                            ManagerNr = 6,
                            Voornaam = "George"
                        },
                        new
                        {
                            PersoneelsNr = 12,
                            ManagerNr = 5,
                            Voornaam = "Loui"
                        },
                        new
                        {
                            PersoneelsNr = 13,
                            ManagerNr = 5,
                            Voornaam = "Pamela"
                        },
                        new
                        {
                            PersoneelsNr = 14,
                            ManagerNr = 5,
                            Voornaam = "Larry"
                        },
                        new
                        {
                            PersoneelsNr = 15,
                            ManagerNr = 5,
                            Voornaam = "Barry"
                        },
                        new
                        {
                            PersoneelsNr = 16,
                            ManagerNr = 4,
                            Voornaam = "Andy"
                        },
                        new
                        {
                            PersoneelsNr = 17,
                            ManagerNr = 4,
                            Voornaam = "Peter"
                        },
                        new
                        {
                            PersoneelsNr = 18,
                            ManagerNr = 4,
                            Voornaam = "Tom"
                        },
                        new
                        {
                            PersoneelsNr = 19,
                            ManagerNr = 2,
                            Voornaam = "Mami"
                        },
                        new
                        {
                            PersoneelsNr = 20,
                            ManagerNr = 19,
                            Voornaam = "Yoshimi"
                        },
                        new
                        {
                            PersoneelsNr = 21,
                            ManagerNr = 5,
                            Voornaam = "Martin"
                        });
                });

            modelBuilder.Entity("Model.Entities.Rekening", b =>
                {
                    b.Property<string>("RekeningNr")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("Rekeningnummer");

                    b.Property<int>("KlantNr")
                        .HasColumnType("int")
                        .HasColumnName("Klant");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Soort")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("RekeningNr");

                    b.HasIndex("KlantNr");

                    b.ToTable("Rekeningen");

                    b.HasData(
                        new
                        {
                            RekeningNr = "123-4567890-02",
                            KlantNr = 1,
                            Saldo = 1000m,
                            Soort = "Z"
                        },
                        new
                        {
                            RekeningNr = "234-5678901-69",
                            KlantNr = 1,
                            Saldo = 2000m,
                            Soort = "S"
                        },
                        new
                        {
                            RekeningNr = "345-6789012-12",
                            KlantNr = 2,
                            Saldo = 500m,
                            Soort = "S"
                        });
                });

            modelBuilder.Entity("Model.Entities.Personeelslid", b =>
                {
                    b.HasOne("Model.Entities.Personeelslid", "Manager")
                        .WithMany("Ondergeschikten")
                        .HasForeignKey("ManagerNr")
                        .HasConstraintName("FK_ManagerNr");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Model.Entities.Rekening", b =>
                {
                    b.HasOne("Model.Entities.Klant", "Klant")
                        .WithMany("Rekeningen")
                        .HasForeignKey("KlantNr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("Model.Entities.Klant", b =>
                {
                    b.Navigation("Rekeningen");
                });

            modelBuilder.Entity("Model.Entities.Personeelslid", b =>
                {
                    b.Navigation("Ondergeschikten");
                });
#pragma warning restore 612, 618
        }
    }
}
